#!/usr/bin/env python3
import sys
import datetime
import pytz
from timewreport.parser import TimeWarriorParser

def isOpenAndToday(interval):
    return (not interval.is_open()) and interval.get_start().date() == datetime.date.today()

def formatTimeDelta(delta):
    return  ":".join(str(delta).split(':')[:2])

parser = TimeWarriorParser(sys.stdin)
intervals = parser.get_intervals()

openIntervals = list(filter(lambda f: f.is_open(), intervals))

todayTasks = "🛑 stopped"
lastDuration = 0

try:
    if len(openIntervals) > 0:
        openInterval = openIntervals[0]
        tags = ",".join(openInterval.get_tags())
        since = openInterval.get_start()
        nDate = datetime.datetime.now(tz=pytz.timezone("Europe/Madrid"))
        lastDuration = nDate - since
        diff = formatTimeDelta(lastDuration)
        todayTasks = f'🗓 {tags} | {diff}'
except:
    pass #todayTasks = "🔥 errored"

try:
    todayIntervals = filter(isOpenAndToday, intervals)
    durations = map(lambda f: f.get_duration(),todayIntervals)
    todayTasks = f'{todayTasks} | {formatTimeDelta(lastDuration + sum(durations,datetime.timedelta()))}'
except:
    pass #todayTasks = "🔥 errored"

print(todayTasks)
